export const POSTS_SET_POSTS = 'POSTS_SET_POSTS';
export const POSTS_UPDATE_POSTS = 'POSTS_UPDATE_POSTS';
export const POSTS_SET_POSTS_LOAD = 'POSTS_SET_POSTS_LOAD';
export const POSTS_SET_CURRENT_PAGE = 'POSTS_SET_CURRENT_PAGE';
export const POSTS_SET_ERROR = 'POSTS_SET_ERROR';
export const POSTS_SET_CAN_LOAD = 'POSTS_SET_CAN_LOAD';
export const POSTS_UPDATE_LIKES = 'POSTS_UPDATE_LIKES';
export const POSTS_DELETE_POST = 'POSTS_DELETE_POST';
export const POSTS_CREATE_POST = 'POSTS_CREATE_POST';
export const POSTS_SET_SHOULD_LOAD = 'POSTS_SET_SHOULD_LOAD';

export const USERS_SET_USERS = 'USERS_SET_USERS';
export const USERS_SET_USERS_LOAD = 'USERS_SET_USERS_LOAD';
export const USERS_SET_CURRENT_PAGE = 'USERS_SET_CURRENT_PAGE';
export const USERS_SET_ERROR = 'USERS_SET_ERROR';
export const USERS_SET_CAN_LOAD = 'USERS_SET_CAN_LOAD';
export const USERS_SET_SHOULD_LOAD = 'USERS_SET_SHOULD_LOAD';
